import SwiftUI
import Combine
import AVFoundation
#if os(watchOS)
import WatchKit
#endif

enum Role { case user, tool, assistant }

struct Line: Identifiable {
    let id = UUID()
    let role: Role
    var text: String
}

enum Phase: Equatable { case idle, thinking, streaming }

/// Runs a Claude-Code session: transcript, the live throbber, the seven PAI Algorithm
/// phases (each announced in voice), and the streamed reply. The reply is generated by
/// Apple's on-device model — directly on iPhone, or relayed from the paired iPhone on the
/// watch — with a local fallback when Apple Intelligence isn't reachable.
@MainActor
final class PAIEngine: ObservableObject {
    @Published var lines: [Line] = []
    @Published var phase: Phase = .idle
    @Published var draft: String = ""

    // throbber state
    @Published var spinnerWord: String = "Cogitating"
    @Published var brailleFrame: String = "⠋"
    @Published var tokens: Int = 0
    @Published var elapsed: Double = 0

    private let braille = ["⠋","⠙","⠹","⠸","⠼","⠴","⠦","⠧","⠇","⠏"]
    private var brailleIdx = 0
    private var ticker: AnyCancellable?
    private var work: Task<Void, Never>?
    private var genTask: Task<String?, Never>?
    private var phasePlayer: AVAudioPlayer?
    private let synth = AVSpeechSynthesizer()

    /// Seconds spent in each pre-stream Algorithm phase. Tune this one number.
    static let phaseSeconds: Double = 10

    let bootTip = Fallback.tips.randomElement() ?? ""

    init() {
        lines = Fallback.seedConversation
    }

    func send() {
        let text = draft.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty, phase == .idle else { return }
        draft = ""
        haptic(.click)
        lines.append(Line(role: .user, text: text))
        announce("phase-observe")                         // 1/7 OBSERVE
        // Kick off real on-device generation now; it lands by the time we stream.
        genTask = Task { [weak self] in await self?.generatedReply(for: text) ?? nil }
        beginThinking()
    }

    // MARK: - Generation

    /// Real on-device generation. iPhone runs the model directly; the watch relays to the
    /// paired iPhone. Returns nil when Apple Intelligence isn't available → caller falls back.
    private func generatedReply(for prompt: String) async -> String? {
        #if os(iOS)
        let text = await Intelligence.shared.respond(to: prompt)
        return text.isEmpty ? nil : text
        #elseif os(watchOS)
        return await Connectivity.shared.requestGeneration(prompt)
        #else
        return nil
        #endif
    }

    // MARK: - Phases

    private func beginThinking() {
        phase = .thinking
        tokens = 0; elapsed = 0; brailleIdx = 0
        spinnerWord = Fallback.spinnerWords.randomElement() ?? "Thinking"

        var wordCountdown = 22
        ticker = Timer.publish(every: 0.08, on: .main, in: .common)
            .autoconnect()
            .sink { [weak self] _ in
                guard let self else { return }
                self.brailleIdx = (self.brailleIdx + 1) % self.braille.count
                self.brailleFrame = self.braille[self.brailleIdx]
                self.elapsed += 0.08
                self.tokens += Int.random(in: 3...18)
                wordCountdown -= 1
                if wordCountdown <= 0 {
                    wordCountdown = 22
                    self.spinnerWord = Fallback.spinnerWords.randomElement() ?? self.spinnerWord
                }
            }

        work = Task { [weak self] in
            guard let self else { return }
            // Phases 2–5: THINK → PLAN → BUILD → EXECUTE, each ~phaseSeconds with tool calls.
            for clip in ["phase-think", "phase-plan", "phase-build", "phase-execute"] {
                if await self.workPhase(seconds: Self.phaseSeconds, tools: 2) == false { return }
                await self.announce(clip)
            }
            if await self.workPhase(seconds: Self.phaseSeconds, tools: 2) == false { return }
            await self.beginStreaming()                    // 6/7 VERIFY → stream → 7/7 LEARN
        }
    }

    /// Spend `seconds` working, surfacing `tools` tool-call lines spaced across the window.
    private func workPhase(seconds: Double, tools: Int) async -> Bool {
        let step = seconds / Double(tools + 1)
        var last = ""
        for _ in 0..<tools {
            try? await Task.sleep(nanoseconds: UInt64(step * 1_000_000_000))
            if Task.isCancelled { return false }
            var tool = Fallback.toolLines.randomElement() ?? ""
            if tool == last { tool = Fallback.toolLines.randomElement() ?? tool }
            last = tool
            lines.append(Line(role: .tool, text: tool))
        }
        try? await Task.sleep(nanoseconds: UInt64(step * 1_000_000_000))
        return !Task.isCancelled
    }

    private func beginStreaming() async {
        ticker?.cancel()
        phase = .streaming
        announce("phase-verify")                           // 6/7 VERIFY

        // Await the on-device generation started at send(); fall back if it didn't land.
        var generated: String? = nil
        if let g = genTask { generated = await g.value }
        let reply = (generated?.isEmpty == false ? generated! : (Fallback.responses.randomElement() ?? "Done."))

        lines.append(Line(role: .assistant, text: ""))
        let idx = lines.count - 1
        for ch in reply {
            if Task.isCancelled || phase != .streaming { return }
            guard lines.indices.contains(idx) else { return }
            lines[idx].text.append(ch)
            let pause: UInt64 = (ch == "\n") ? 110_000_000 : (".!?".contains(ch) ? 75_000_000 : 22_000_000)
            try? await Task.sleep(nanoseconds: pause)
        }
        guard phase == .streaming else { return }
        haptic(.success)
        announce("phase-learn")                            // 7/7 LEARN
        phase = .idle
        // Speak the generated summary in the native Australian "Lee" voice, after the clip.
        let summary = reply
        Task { [weak self] in
            try? await Task.sleep(nanoseconds: 1_300_000_000)
            self?.speakSummary(summary)
        }
    }

    func interrupt() {
        work?.cancel()
        genTask?.cancel()
        ticker?.cancel()
        synth.stopSpeaking(at: .immediate)
        if phase != .idle {
            lines.append(Line(role: .tool, text: "⎿ Interrupted by user"))
            announce("phase-interrupt")
        }
        phase = .idle
        haptic(.directionDown)
    }

    // MARK: - Audio

    /// Plays a bundled phase clip (ElevenLabs "Ashley") through the device speaker.
    private func announce(_ clip: String) {
        guard let url = Bundle.main.url(forResource: clip, withExtension: "mp3") else { return }
        do {
            #if os(watchOS) || os(iOS)
            let session = AVAudioSession.sharedInstance()
            try session.setCategory(.playback, mode: .default, options: [.duckOthers])
            try session.setActive(true)
            #endif
            phasePlayer?.stop()
            let p = try AVAudioPlayer(contentsOf: url)
            p.volume = 1.0
            p.play()
            phasePlayer = p
        } catch { }
    }

    /// Speaks the generated summary using Apple's native on-device TTS (Australian "Lee").
    private func speakSummary(_ text: String) {
        let clean = text
            .replacingOccurrences(of: "•", with: "")
            .replacingOccurrences(of: "\n", with: ". ")
        let utt = AVSpeechUtterance(string: clean)
        utt.voice = Self.auVoice
        utt.rate = AVSpeechUtteranceDefaultSpeechRate
        #if os(watchOS) || os(iOS)
        let s = AVAudioSession.sharedInstance()
        try? s.setCategory(.playback, mode: .spokenAudio, options: [.duckOthers])
        try? s.setActive(true)
        #endif
        synth.speak(utt)
    }

    /// Prefer the Australian "Lee" voice; fall back to any en-AU voice.
    static let auVoice: AVSpeechSynthesisVoice? = {
        let voices = AVSpeechSynthesisVoice.speechVoices()
        return voices.first { $0.name.localizedCaseInsensitiveContains("Lee") && $0.language.hasPrefix("en-AU") }
            ?? voices.first { $0.language == "en-AU" }
            ?? AVSpeechSynthesisVoice(language: "en-AU")
    }()

    private func haptic(_ t: HapticType) {
        #if os(watchOS)
        WKInterfaceDevice.current().play(t.wk)
        #endif
    }
}

enum HapticType {
    case click, success, directionDown
    #if os(watchOS)
    var wk: WKHapticType {
        switch self {
        case .click: return .click
        case .success: return .success
        case .directionDown: return .directionDown
        }
    }
    #endif
}
